version: 0.2

# TODO
#   - is it ok that artifacts phase is executed even if the BUILD phase fails
#       https://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases
#   - publish to crates.io

env:
  variables:
    # expected
    OSNAME: ""
    MODULES: ""
    # optional
    ARTIFACTS: ""

phases:

  pre_build:
    commands:
      - echo Pre-Build started on `date`
      - mkdir -p /tmp/artifacts/logs
  build:
    commands:
      - echo Build started on `date`
      - printenv
      - |
        set -ex
        pipenv --three
        pipenv run pip install .[tests]
        for module in $MODULES; do
            echo "Testing '$module'"
            /bin/bash -c "set -o pipefail; pipenv run python -m pytest -l --junit-xml=/tmp/artifacts/logs/test.${module}.xml ${module} | tee /tmp/artifacts/logs/test.${module}.log"
        done

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts
      - find /tmp/artifacts

artifacts:
  # (for now CodeBuild doesn't allow to use env variables in artifacts phase)
  # https://forums.aws.amazon.com/thread.jspa?threadID=250742
  base-directory: /tmp/artifacts
  files:
      - '**/*'
